In [1]:
import numpy as np 
import pandas as pd 
import math as m
np.set_printoptions(suppress=True)

In [2]:
visine = pd.read_csv('Visine.csv')
visine = np.asarray(visine)

In [3]:
k=visine
k


array([[  0.    ,   0.    ,  20.    ,  40.    ],
       [  0.    ,   6.554 ,   7.071 ,   6.626 ],
       [ 20.    ,   6.323 ,   6.681 ,   6.593 ],
       [ 40.    ,   6.214 ,   6.368 ,   6.444 ],
       [ 60.    ,   6.74  ,   6.759 ,   6.114 ],
       [ 80.    ,   6.0675,   6.29  ,   6.539 ],
       [100.    ,   6.525 ,   6.86  ,   6.998 ],
       [120.    ,   6.012 ,   6.657 ,   7.121 ],
       [140.    ,   6.812 ,   7.19  ,   7.437 ]])

In [4]:
def matricaA(visine):
    A = np.zeros(((visine.shape[0]-1)*(visine.shape[1]-1),3))
    A[:,0]=1
    A[:,1]=np.repeat(-visine[0,1:],visine.shape[0]-1)
    A[:,2]=np.tile(-visine[1:,0],visine.shape[1]-1)
    
    return A

In [5]:
def matricaF(visine):
    F = -visine[1:,1:].flatten('F')
    F = F.reshape(-1,1)
    return F
F = matricaF(k)
F

array([[-6.554 ],
       [-6.323 ],
       [-6.214 ],
       [-6.74  ],
       [-6.0675],
       [-6.525 ],
       [-6.012 ],
       [-6.812 ],
       [-7.071 ],
       [-6.681 ],
       [-6.368 ],
       [-6.759 ],
       [-6.29  ],
       [-6.86  ],
       [-6.657 ],
       [-7.19  ],
       [-6.626 ],
       [-6.593 ],
       [-6.444 ],
       [-6.114 ],
       [-6.539 ],
       [-6.998 ],
       [-7.121 ],
       [-7.437 ]])

In [6]:
A = matricaA(k)

In [27]:
def neuslovljena(visine,A,F):
    nn,u = A.shape
    N = np.matmul(A.transpose(),A)
    Qx = np.linalg.inv(N)
    n = np.matmul(A.transpose(),F)
    x = np.matmul(-Qx,n)
    x = x.reshape(-1,1)
    v = np.matmul(A,x) + F
    sigma_o = m.sqrt(np.matmul(v.transpose(),v)/(nn-u))
    sigma_lm = sigma_o*np.sqrt(np.diag(Qx))

    
    return N,Qx,n,x,v,sigma_o,sigma_lm 

In [28]:
N,Qx,n,x,v,sigma_o,sigma_lm = neuslovljena(k,A,F)

In [38]:
v

array([[-0.26871181],
       [ 0.01242907],
       [ 0.17156994],
       [-0.30428919],
       [ 0.41835169],
       [ 0.01099256],
       [ 0.57413343],
       [-0.17572569],
       [-0.62168056],
       [-0.18153968],
       [ 0.18160119],
       [-0.15925794],
       [ 0.35988294],
       [-0.15997619],
       [ 0.09316468],
       [-0.38969444],
       [-0.01264931],
       [ 0.07049157],
       [ 0.26963244],
       [ 0.64977331],
       [ 0.27491419],
       [-0.13394494],
       [-0.20680407],
       [-0.47266319]])

In [29]:
def uslovljena(visine,A,F,tacke):
    nn,u = A.shape
    N = np.matmul(A.transpose(),A)
    if len(tacke)==2:
        B = np.array([1,-tacke[0],-tacke[1]]).reshape(1,-1)
        yidx = np.where(k[0,:]==tacke[0])
        xidx = np.where(k[:,0]==tacke[1])
        kx =-k[xidx[0][0],yidx[0][0]]
    elif len(tacke)==4:
        B = np.array([[1,-tacke[0],-tacke[1]],[1,-tacke[2],-tacke[3]]])
        y1idx = np.where(k[0,:]==tacke[0])
        x1idx = np.where(k[:,0]==tacke[1])
        y2idx = np.where(k[0,:]==tacke[2])
        x2idx = np.where(k[:,0]==tacke[3])
        k1=-k[x1idx[0][0],y1idx[0][0]]
        k2 =-k[x2idx[0][0],y2idx[0][0]]
        kx = np.vstack((k1,k2))

    N = np.hstack((np.vstack((N,B)),np.vstack((B.transpose(),np.zeros((B.shape[0],B.shape[0]))))))
    Qx = np.linalg.inv(N)
    n = np.matmul(A.transpose(),F)
    n = np.vstack((n,kx))
    x = np.matmul(-Qx,n)
    x1 = x[:-kx.size]
    x1 = x1.reshape(-1,1)
    v = np.matmul(A,x1) + F
    sigma_o = m.sqrt(np.matmul(v.transpose(),v)/(nn-u))
    sigma_lm = sigma_o*np.sqrt(np.diag(Qx[:-kx.size,:-kx.size]))

    return N,Qx,n,x,v,sigma_o,sigma_lm ,B

In [7]:
def odstampajResenja(A,F,N,Qx,n,x,v,sigma_o,sigma_lm ,B):
    print('Matrica A')
    print(A)
    print('Matrica F  ')
    print(F)
    print(' Matrica N')
    print(N1)
    print(' Matrica Qx ')
    print(Qx1)
    print(' Matrica n')
    print(n1)
    print(' Vektor x ')
    print(x1)
    print('Popravke v ')
    print(v1)
    print(' A posteriori standardna devijacija ')
    print(sigma_o1)
    print('Standardne devijacije nepoznatih parametara ')
    print(sigma_lm1)
    print(' Matrica B1 ')
    print(B1)
    print(' ')

In [11]:
tacke1 = [60,120]


N1,Qx1,n1,x1,v1,sigma_o1,sigma_lm1 ,B1 = uslovljena(k,A,F,tacke1)

odstampajResenja(A,F,N1,Qx1,n1,x1,v1,sigma_o1,sigma_lm1 ,B1)

In [13]:
tacke2 = [0,120,40,0]

In [ ]:

N2,Qx2,n2,x2,v2,sigma_o2,sigma_lm2 ,B2 = uslovljena(k,A,F,tacke2)

odstampajResenja(A,F,N2,Qx2,n2,x2,v2,sigma_o2,sigma_lm2 ,B2)

In [ ]:
len(tacke2)

In [15]:
tacke = [0,120,40,0]

nn,u = A.shape
N = np.matmul(A.transpose(),A)
if len(tacke)==2:
    B = np.array([1,-tacke[0],-tacke[1]]).reshape(1,-1)
    yidx = np.where(k[0,:]==tacke[0])
    xidx = np.where(k[:,0]==tacke[1])
    kx =-k[xidx[0][0],yidx[0][0]]
elif len(tacke)==4:
    B = np.array([[1,-tacke[0],-tacke[1]],[1,-tacke[2],-tacke[3]]])
    y1idx = np.where(k[0,:]==tacke[0])
    x1idx = np.where(k[:,0]==tacke[1])
    y2idx = np.where(k[0,:]==tacke[2])
    x2idx = np.where(k[:,0]==tacke[3])
    k1=-k[x1idx[0][0],y1idx[0][0]]
    k2 =-k[x2idx[0][0],y2idx[0][0]]
    kx = np.vstack((k1,k2))

kx[0][0] = -6.012
kx[1][0] = -6.626
N = np.hstack((np.vstack((N,B)),np.vstack((B.transpose(),np.zeros((B.shape[0],B.shape[0]))))))
Qx = np.linalg.inv(N)
n = np.matmul(A.transpose(),F)
n = np.vstack((n,kx))
x = np.matmul(-Qx,n)
x1 = x[:-kx.size]
x1 = x1.reshape(-1,1)
v = np.matmul(A,x1) + F
sigma_o = m.sqrt(np.matmul(v.transpose(),v)/(nn-u))
sigma_lm = sigma_o*np.sqrt(np.diag(Qx[:-kx.size,:-kx.size]))